<?php

namespace User\UserBundle\Repository;

/**
 * UsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsRepository extends \Doctrine\ORM\EntityRepository
{
}
